---
name: ExampleOS
steps:
  - step: ostree_init
    options:
      repo: /var/wwww/html/repo
      mode: bare
  - step: ostree_prep
    options:
      repo: /var/www/html/repo
      branch: exampleos/testing
      target: rootfs.tar.gz
