---
name: ExampleOS-ostree
steps:
  - step: ostree_deploy
    options:
      repo: /var/www/html/repo
      branch: exampleos/testing
      image: disk.img
      kernel_args:
        - root=LABEL=ROOT
        - rw
        - console=tty0
        - console=ttyS0,115200n8
