---
name: ExampleOS-ostree
steps:
  - step: image
    options:
      image:
        name: disk.img
        size: 10G
        # gpt / msdos
        label: gpt
      partitions:
        - name: EFI
          start: 0%
          end: 256MB
          type: "c12a7328-f81f-11d2-ba4b-00a0c93ec93b"
          flags: [boot, esp]
        - name: ROOT
          start: 256MB
          end: 100%
          type: "4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709"
      filesystems:
        - name: EFI
          label: EFI
          fs: vfat
          options: []
        - name: ROOT
          label: ROOT
          fs: ext4
          options: []

